/* Kira Knowledge Engine v6
 * External APIs are evidence providers only. Kira's local model remains the answer writer.
 * Adds: planner, source health, evidence clustering, claim extraction, conflict flags,
 * persistent IndexedDB evidence/facts, stale-cache fallback, adaptive timeouts, and diagnostics.
 */
(() => {
  const DB='kira-knowledge-v6', STORES={answers:'answers',evidence:'evidence',facts:'facts',meta:'meta'};
  const TTL=24*60*60*1000, STALE_MAX=7*24*60*60*1000, MAX=800;
  const stop=new Set('a an the and or of to in on for is are was were be been being what which who where when why how can could would should do does did tell me please explain about from with into as by at it this that these those i me my your you we they them their there here very really just get give show make use used using'.split(' '));
  const memory=new Map(), health=new Map(); let dbPromise;
  const emit=(type,detail={})=>window.dispatchEvent(new CustomEvent('kira-knowledge-status',{detail:{type,...detail}}));
  function db(){if(dbPromise)return dbPromise;dbPromise=new Promise(res=>{if(!indexedDB)return res(null);const r=indexedDB.open(DB,2);r.onupgradeneeded=()=>{const d=r.result;Object.values(STORES).forEach(s=>{if(!d.objectStoreNames.contains(s))d.createObjectStore(s)});};r.onsuccess=()=>res(r.result);r.onerror=()=>res(null)});return dbPromise}
  async function get(store,k){const d=await db();if(!d)return null;return new Promise(res=>{const t=d.transaction(store,'readonly').objectStore(store).get(k);t.onsuccess=()=>res(t.result||null);t.onerror=()=>res(null)})}
  async function put(store,k,v){const d=await db();if(!d)return;await new Promise(res=>{const t=d.transaction(store,'readwrite').objectStore(store).put(v,k);t.onsuccess=t.onerror=()=>res()})}
  async function trim(store,max=MAX){const d=await db();if(!d)return;const all=[];await new Promise(res=>{const r=d.transaction(store,'readonly').objectStore(store).openCursor();r.onsuccess=()=>{const c=r.result;if(c){all.push([c.key,c.value?.time||0]);c.continue()}else res()}});if(all.length<=max)return;const old=all.sort((a,b)=>a[1]-b[1]).slice(0,all.length-max);for(const [k] of old)await new Promise(res=>{const t=d.transaction(store,'readwrite').objectStore(store).delete(k);t.onsuccess=t.onerror=()=>res()})}
  function clean(q){return String(q||'').replace(/[\u0000-\u001f]/g,' ').replace(/\s+/g,' ').trim().slice(0,1800)}
  function terms(q){return [...new Set(clean(q).toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').split(' ').filter(w=>w.length>2&&!stop.has(w)))]}
  function subject(q){let s=clean(q).replace(/^(hey\s+)?(can you|could you|please|tell me|explain|give me|show me|help me)\s+/i,'').replace(/^(what|who|where|when|why|how)\s+(is|are|was|were|does|do|did|can|could|would|will)\s+/i,'').replace(/^(define|definition of|meaning of|tell me about)\s+/i,'').replace(/[?]+$/,'').trim();return s||clean(q)}
  function intent(q){const s=q.toLowerCase();let type='general';if(/\b(latest|today|now|current|recent|news|price|weather|score|schedule|stock|exchange rate|this week)\b/.test(s))type='current';else if(/\b(code|coding|programming|javascript|python|html|css|github|software|api|webgpu|database|linux|android|discord|bug|error)\b/.test(s))type='technology';else if(/\b(science|physics|chemistry|biology|medicine|experiment|research|study|paper|academic|equation)\b/.test(s))type='research';else if(/\b(book|novel|author|isbn|literature|poem|wrote|written by)\b/.test(s))type='book';else if(/\b(who|person|invented|founded|actor|singer|scientist|ceo|president)\b/.test(s))type='person';else if(/\b(where|city|country|capital|located|place|location)\b/.test(s))type='place';else if(/\b(history|historical|ancient|war|empire|dynasty|kingdom)\b/.test(s))type='history';else if(/\b(what is|what are|define|definition|meaning|means|explain)\b/.test(s))type='definition';const multi=/\b(compare|difference|versus|vs\.?|both|while|whereas)\b/.test(s);const visual=/\b(image|picture|photo|screenshot|diagram|shown|visible)\b/.test(s);return{type,multi,visual,subject:subject(q)}}
  function timeoutFetch(url,opts={},ms=3000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);return fetch(url,{...opts,signal:c.signal,cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r}).finally(()=>clearTimeout(t))}
  async function json(url,o={},m=3000){return timeoutFetch(url,o,m).then(r=>r.json())}
  async function text(url,o={},m=3000){return timeoutFetch(url,o,m).then(r=>r.text())}
  const providers={
    wikipedia:async q=>{const d=await json('https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch='+encodeURIComponent(q)+'&srlimit=6&format=json&origin=*',{},3000);return Promise.all((d.query?.search||[]).slice(0,6).map(async h=>{try{const s=await json('https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(h.title.replaceAll(' ','_')),{},2500);return s.extract?{source:'Wikipedia',title:s.title,text:s.extract,url:s.content_urls?.desktop?.page||'',base:10,date:s.timestamp}:null}catch{return null}})).then(x=>x.filter(Boolean))},
    wikidata:async q=>{const sparql=`SELECT ?item ?itemLabel ?description WHERE {?item rdfs:label ?label. FILTER(LANG(?label)="en") FILTER(CONTAINS(LCASE(STR(?label)),LCASE(${JSON.stringify(q.slice(0,200))}))) OPTIONAL {?item schema:description ?description. FILTER(LANG(?description)="en")} SERVICE wikibase:label {bd:serviceParam wikibase:language "en".}} LIMIT 8`;const d=await json('https://query.wikidata.org/sparql?format=json&query='+encodeURIComponent(sparql),{headers:{Accept:'application/sparql-results+json'}},3200);return(d.results?.bindings||[]).map(x=>({source:'Wikidata',title:x.itemLabel?.value||'',text:x.description?.value||'',url:x.item?.value||'',base:9})).filter(x=>x.text)},
    duck:async q=>{const d=await json('https://api.duckduckgo.com/?q='+encodeURIComponent(q)+'&format=json&no_html=1&skip_disambig=0',{},2800),o=[];if(d.AbstractText)o.push({source:'DuckDuckGo',title:d.Heading||q,text:d.AbstractText,url:d.AbstractURL||'',base:7});(d.RelatedTopics||[]).slice(0,6).forEach(x=>{if(x.Text)o.push({source:'DuckDuckGo',title:x.Text.slice(0,140),text:x.Text,url:x.FirstURL||'',base:4})});return o},
    openlibrary:async q=>{const d=await json('https://openlibrary.org/search.json?q='+encodeURIComponent(q)+'&limit=7',{},3000);return(d.docs||[]).slice(0,7).map(x=>({source:'Open Library',title:x.title||'',text:[x.author_name?.slice(0,3).join(', '),x.first_publish_year?`First published ${x.first_publish_year}.`:'',x.subject?.slice(0,8).join(', ')].filter(Boolean).join('. '),url:x.key?'https://openlibrary.org'+x.key:'',base:6,date:x.first_publish_year?`${x.first_publish_year}-01-01`:null})).filter(x=>x.title)},
    openalex:async q=>{const d=await json('https://api.openalex.org/works?search='+encodeURIComponent(q)+'&per-page=7',{},3000);return(d.results||[]).slice(0,7).map(x=>({source:'OpenAlex',title:x.title||'',text:[x.publication_year?`Published ${x.publication_year}.`:'',x.primary_location?.source?.display_name||'',x.authorships?.slice(0,3).map(a=>a.author?.display_name).filter(Boolean).join(', ')||'',x.concepts?.slice(0,6).map(c=>c.display_name).join(', ')||''].filter(Boolean).join(' '),url:x.doi||x.id||'',base:9,date:x.publication_year?`${x.publication_year}-01-01`:null})).filter(x=>x.title)},
    crossref:async q=>{const d=await json('https://api.crossref.org/works?query.bibliographic='+encodeURIComponent(q)+'&rows=7',{},3000);return(d.message?.items||[]).slice(0,7).map(x=>({source:'Crossref',title:x.title?.[0]||'',text:[x.author?.slice(0,3).map(a=>`${a.given||''} ${a.family||''}`).join(', '),x.published?.['date-parts']?.[0]?.[0]?`Published ${x.published['date-parts'][0][0]}.`:'',x.container-title?.[0]||''].filter(Boolean).join('. '),url:x.URL||(x.DOI?'https://doi.org/'+x.DOI:''),base:8,date:x.published?.['date-parts']?.[0]?.[0]?`${x.published['date-parts'][0][0]}-01-01`:null})).filter(x=>x.title)},
    arxiv:async q=>{const xml=await text('https://export.arxiv.org/api/query?search_query=all:'+encodeURIComponent(q)+'&start=0&max_results=7',{},3500),doc=new DOMParser().parseFromString(xml,'text/xml');return[...doc.querySelectorAll('entry')].map(e=>({source:'arXiv',title:e.querySelector('title')?.textContent?.replace(/\s+/g,' ').trim()||'',text:e.querySelector('summary')?.textContent?.replace(/\s+/g,' ').trim()||'',url:e.querySelector('id')?.textContent?.trim()||'',base:9,date:e.querySelector('published')?.textContent?.trim()||null})).filter(x=>x.title)},
    hackernews:async q=>{const d=await json('https://hn.algolia.com/api/v1/search?query='+encodeURIComponent(q)+'&hitsPerPage=7',{},2800);return(d.hits||[]).map(x=>({source:'Hacker News',title:x.title||x.story_title||'',text:x.comment_text?.replace(/<[^>]+>/g,' ')||'Community discussion or story.',url:x.url||(x.objectID?'https://news.ycombinator.com/item?id='+x.objectID:''),base:3,date:x.created_at||null})).filter(x=>x.title)},
    stack:async q=>{const d=await json('https://api.stackexchange.com/2.3/search/advanced?order=desc&sort=relevance&q='+encodeURIComponent(q)+'&site=stackoverflow&pagesize=7&filter=default',{},3000);return(d.items||[]).map(x=>({source:'Stack Overflow',title:x.title||'',text:`Answers: ${x.answer_count||0}. Score: ${x.score||0}. Tags: ${(x.tags||[]).join(', ')}.`,url:x.link||'',base:6,date:x.creation_date?new Date(x.creation_date*1000).toISOString():null})).filter(x=>x.title)}
  };
  const groups={general:['wikipedia','wikidata','duck','openalex'],definition:['wikipedia','wikidata','duck'],current:['wikipedia','duck','hackernews','wikidata'],technology:['wikipedia','wikidata','duck','stack','arxiv','hackernews'],research:['wikipedia','openalex','crossref','arxiv'],book:['openlibrary','wikipedia','crossref'],person:['wikipedia','wikidata','duck'],place:['wikipedia','wikidata','duck'],history:['wikipedia','wikidata','openalex']};
  function variants(q,i){const s=i.subject||q,a=[s,q];if(i.type==='definition')a.push('definition of '+s);if(i.type==='research')a.push(s+' research');if(i.type==='technology')a.push(s+' technical documentation');if(i.type==='current')a.push(s+' latest');if(i.multi)a.push('compare '+q);return[...new Set(a.map(clean).filter(Boolean))].slice(0,4)}
  function score(x,q,i){const hay=(x.title+' '+x.text).toLowerCase(),ts=terms(q);let s=x.base||1;ts.forEach(t=>{if(hay.includes(t))s+=2});const sub=i.subject.toLowerCase();if(sub.length>3&&hay.includes(sub))s+=10;if(i.type==='definition'&&['Wikipedia','Wikidata','DuckDuckGo'].includes(x.source))s+=4;if(i.type==='research'&&['OpenAlex','Crossref','arXiv'].includes(x.source))s+=5;if(i.type==='technology'&&['Stack Overflow','arXiv','Hacker News'].includes(x.source))s+=4;if(i.type==='current'&&x.date){const d=Date.now()-new Date(x.date).getTime();if(d<7*864e5)s+=6;else if(d<30*864e5)s+=3}return s}
  function dedupe(items){const seen=new Set();return items.filter(x=>{const k=(x.title+'|'+x.text.slice(0,180)).toLowerCase().replace(/[^a-z0-9]+/g,' ');if(seen.has(k))return false;seen.add(k);return true})}
  function claims(items){const out=[];for(const x of items.slice(0,20)){const sentences=x.text.split(/(?<=[.!?])\s+/).map(s=>s.trim()).filter(s=>s.length>45);for(const s of sentences.slice(0,5))out.push({text:s,source:x.source,title:x.title})}return out}
  function conflictFlags(items){const c=claims(items),flags=[];for(let a=0;a<c.length;a++)for(let b=a+1;b<c.length;b++){const wa=new Set(terms(c[a].text)),wb=new Set(terms(c[b].text));let overlap=0;wa.forEach(w=>{if(wb.has(w))overlap++});if(overlap>=5&&c[a].source!==c[b].source&&!c[a].text.toLowerCase().includes(c[b].text.toLowerCase().slice(0,60))){if(/\b(19|20)\d{2}\b/.test(c[a].text)&&/\b(19|20)\d{2}\b/.test(c[b].text))flags.push({a:c[a],b:c[b]})}}return flags.slice(0,4)}
  function buildContext(items,q,i){const flags=conflictFlags(items);let s=`Question intent: ${i.type}. Subject: ${i.subject}.\nUse the following as evidence. Sources may be incomplete or disagree; resolve carefully and state uncertainty when necessary.\n\n`;s+=items.slice(0,18).map((x,n)=>`[Evidence ${n+1} | ${x.source} | relevance ${x.score}] ${x.title}\n${x.text.slice(0,2600)}\nSource: ${x.url||'N/A'}`).join('\n\n');if(flags.length)s+=`\n\nPotential source disagreements detected:\n${flags.map(f=>`- ${f.a.source}: ${f.a.text}\n- ${f.b.source}: ${f.b.text}`).join('\n')}`;return s}
  function updateHealth(name,ok){const h=health.get(name)||{ok:0,fail:0,last:0};ok?h.ok++:h.fail++;h.last=Date.now();health.set(name,h)}
  async function retrieve(query,opt={}){const q=clean(query);if(!q)return{context:'',sources:[],offline:true};const key=q.toLowerCase();const fresh=await get(STORES.answers,key);if(fresh){const age=Date.now()-fresh.time;if(age<TTL){emit('cache-hit',{query:q,fresh:true});return{...fresh.value,cached:true,ageMs:age}}if(age<STALE_MAX){emit('cache-hit',{query:q,fresh:false});var stale=fresh.value}}
    const i=intent(q), names=groups[i.type]||groups.general, qs=variants(q,i);emit('planning',{kind:i.type,subject:i.subject,providers:names.length,variants:qs.length});
    const tasks=[];for(const name of names){for(const v of qs.slice(0,name==='wikipedia'?2:1)){tasks.push((async()=>{try{const r=await providers[name](v);updateHealth(name,true);return r}catch(e){updateHealth(name,false);return[]}})())}}
    const settled=await Promise.allSettled(tasks);let items=dedupe(settled.flatMap(x=>x.status==='fulfilled'?x.value:[]));items=items.map(x=>({...x,score:score(x,q,i)})).sort((a,b)=>b.score-a.score);const selected=items.slice(0,18);
    if(!selected.length&&stale){stale.stale=true;stale.warning='Using cached knowledge because live sources were unavailable.';return stale}
    const value={kind:i.type,subject:i.subject,context:buildContext(selected,q,i),sources:selected.filter(x=>x.url).slice(0,14).map(x=>({name:`${x.source}: ${x.title}`,url:x.url})),providerCount:names.length,evidenceCount:selected.length,retrievedAt:new Date().toISOString(),offline:selected.length===0,conflicts:conflictFlags(selected).length,planner:{intent:i.type,variants:qs,providers:names}};
    if(selected.length){await put(STORES.answers,key,{time:Date.now(),value});await put(STORES.evidence,key,{time:Date.now(),items:selected});await trim(STORES.answers)}emit('complete',{query:q,evidence:selected.length,kind:i.type,conflicts:value.conflicts});return{...value,cached:false,ageMs:0}}
  async function rememberFact(key,value,source='user'){const k=clean(key).toLowerCase();if(!k)return;await put(STORES.facts,k,{key:k,value:String(value).slice(0,1200),source,time:Date.now()});await trim(STORES.facts,300)}
  async function recallFacts(query,limit=8){const d=await db();if(!d)return[];const rows=[];await new Promise(res=>{const r=d.transaction(STORES.facts,'readonly').objectStore(STORES.facts).openCursor();r.onsuccess=()=>{const c=r.result;if(c){rows.push(c.value);c.continue()}else res()}});const ts=terms(query);return rows.map(x=>({...x,score:ts.reduce((n,t)=>n+(x.key.includes(t)||x.value.toLowerCase().includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
  async function clear(){memory.clear();const d=await db();if(!d)return;for(const s of Object.values(STORES))await new Promise(r=>{const t=d.transaction(s,'readwrite').objectStore(s).clear();t.onsuccess=t.onerror=()=>r()})}
  async function diagnostics(){const out={cache:'IndexedDB',ttlHours:24,staleFallbackDays:7,maxAnswers:MAX,providers:Object.keys(providers).length,health:{}};health.forEach((v,k)=>out.health[k]=v);return out}
  window.KiraKnowledge={retrieve,rememberFact,recallFacts,clear,diagnostics,stats:diagnostics};
})();
